{% set name = "unitpackage" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unitpackage-{{ version }}.tar.gz
  sha256: 19e12af11c331770c9a7a2558b03a164404b5b626370c395c0c49cef49e48de6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - astropy-base >=5,<8
    - frictionless >=5.8.3,<6
    - matplotlib-base >=3.5.0,<4
    - pandas >=1.3,<3
    - plotly >=5,<7
    - pybtex >=0.25,<0.26

test:
  imports:
    - unitpackage
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/unitpackage/
  summary: a Python library to interact with a collection of frictionless datapackages
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://echemdb.github.io/unitpackage/
  dev_url: https://github.com/echemdb/unitpackage

extra:
  recipe-maintainers:
    - DunklesArchipel
    - saraedum
    - linuxrider
