{% set name = "unitpackage" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unitpackage-{{ version }}.tar.gz
  sha256: c762b4b3c69ceca0d3a052f9537f6f4453256a265d2dfaa0d18643d2b72de881

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - astropy-base >=5,<6
    - filelock >=3,<4
    - frictionless >=5.10.1,<6
    - matplotlib-base >=3.5.0,<4
    - pandas >=2,<3
    - plotly >=5,<6
    - pybtex >=0.24,<0.25

test:
  imports:
    - unitpackage
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/unitpackage/
  summary: a Python library to interact with a collection of frictionless datapackages
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://echemdb.github.io/unitpackage/
  dev_url: https://github.com/echemdb/unitpackage

extra:
  recipe-maintainers:
    - DunklesArchipel
    - saraedum
    - linuxrider
