{% set name = "unitpackage" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unitpackage-{{ version }}.tar.gz
  sha256: 61916e2b602a3ed34cd7a27354ca8935b24392bbaf82f37dd65050fd314661ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - astropy-base >=5,<7
    - filelock >=3,<4
    - frictionless >=5.8.3,<6
    - iteration_utilities >=0.13.0,<0.14.0
    - matplotlib-base >=3.5.0,<4
    - pandas >=1.3,<3
    - plotly >=5,<6
    - pybtex >=0.24,<0.25

test:
  imports:
    - unitpackage
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/unitpackage/
  summary: a Python library to interact with a collection of frictionless datapackages
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://echemdb.github.io/unitpackage/
  dev_url: https://github.com/echemdb/unitpackage

extra:
  recipe-maintainers:
    - DunklesArchipel
    - saraedum
    - linuxrider
