{% set name = "unitpackage" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unitpackage-{{ version }}.tar.gz
  sha256: d79951d493a5b9cb1564138bc192cd79052d995f1e46d3ca5c96071301e2dab7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - astropy >=5,<6
    - filelock >=3,<4
    - frictionless >=5.10.1,<6
    - matplotlib-base >=3.5.0,<4
    - pandas >=1,<2
    - plotly >=5,<6
    - pybtex >=0.24,<0.25
    - svgdigitizer >=0.10.0,<0.11.0

test:
  imports:
    - unitpackage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/unitpackage/
  summary: a Python library to interact with a collection of frictionless datapackages
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://echemdb.github.io/unitpackage/
  dev_url: https://github.com/echemdb/unitpackage

extra:
  recipe-maintainers:
    - DunklesArchipel
    - saraedum
    - linuxrider
