{% set name = "unitpackage" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unitpackage-{{ version }}.tar.gz
  sha256: 2944255c0b0eaf05598032b67a744d7efdc18a060ab26eadf6ef0f8a82cf2958

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - astropy >=5,<6
    - filelock >=3,<4
    - frictionless >=5.10.1,<6
    - matplotlib-base >=3.5.0,<4
    - pandas >=2,<3
    - plotly >=5,<6
    - pybtex >=0.24,<0.25

test:
  imports:
    - unitpackage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/unitpackage/
  summary: a Python library to interact with a collection of frictionless datapackages
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://echemdb.github.io/unitpackage/
  dev_url: https://github.com/echemdb/unitpackage

extra:
  recipe-maintainers:
    - DunklesArchipel
    - saraedum
    - linuxrider
